KEY_OVERRIDE_ENABLE = yes
NKRO_ENABLE = yes
POINTING_DEVICE_ENABLE = yes

# combos 
VPATH  +=  keyboards/gboards
COMBO_ENABLE = yes

# mouse
MOUSEKEY_ENABLE = yes

BOOTMAGIC_ENABLE = yes
EXTRAKEY_ENABLE = yes

SWAP_HANDS_ENABLE = yes

# joystick
JOYSTICK_ENABLE = yes
JOYSTICK_DRIVER = digital