#define TAPPING_TERM 250

#define COMBO_VARIABLE_LEN
#define COMBO_TERM 50

#define MK_3_SPEED

#define MK_C_OFFSET_0 4
#define MK_C_OFFSET_1 16
#define MK_C_OFFSET_2 64

#define IGNORE_MOD_TAP_INTERRUPT
#define PERMISSIVE_HOLD