#pragma once

//  bootloader shit (press q)
#define BOOTMAGIC_ROW 0
#define BOOTMAGIC_COLUMN 0

//  cirque
#define CIRQUE_PINNACLE_POSITION_MODE  CIRQUE_PINNACLE_ABSOLUTE_MODE
#define CIRQUE_PINNACLE_TAP_ENABLE

#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE

#define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE 
