SRC += muse.c
AUDIO_ENABLE = yes
MIDI_ENABLE = no
SWAP_HANDS_ENABLE = yes
AUDIO_DRIVER = dac_additive
RGBLIGHT_ENABLE = yes
COMBO_ENABLE = yes

TAP_DANCE_ENABLE = no
UNICODEMAP_ENABLE = no

MOUSEKEY_ENABLE = no
BOOTMAGIC_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
MOUSEKEY_ENABLE = no
